const sampleBooks = [
  {
    title: "Introduction to Algorithms",
    description: "A comprehensive guide on algorithms, data structures, and problem-solving techniques.",
    author: "Thomas H. Cormen",
    price: 450,
    imageUrl:"https://covers.openlibrary.org/b/id/6709987-L.jpg",
    category: "Technology",
    quantity:1,
  },
  {
    title: "Engineering Physics",
    description: "Covers fundamental physics concepts required for engineering students.",
    author: "S.L. Arora",
    price: 220,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPg55KyH77N-oZ75V3pxzsdUmGYKUeeok84Q&s",
    category: "Science",
    quantity:1,
  },
  {
    title: "Basic Electrical Engineering",
    description: "A clear introduction to electrical circuits, machines, and systems.",
    author:"D.C. Kulshreshtha",
    price: 300,
    imageUrl: "https://covers.openlibrary.org/b/id/15117670-L.jpg",
    category: "Science",
    quantity:1,
  },
  {
    title: "Discrete Mathematics",
    description: "Explains logic, sets, probability, graphs, and mathematical reasoning.",
    author:"Kenneth Rosen",
    price: 260,
    imageUrl: "https://covers.openlibrary.org/b/id/1135125-L.jpg",
    category: "Mathematics",
    quantity:1
  },
  {
    title: "Operating Systems Concepts",
    description: "Learn how operating systems manage processes, memory, files, and hardware.",
    author:"Abraham Silberschatz",
    price: 380,
    imageUrl: "https://covers.openlibrary.org/b/id/135285-L.jpg",
    category: "Education",
    quantity:1,
  },
  {
    title: "Engineering Chemistry",
    description: "Detailed explanation of chemical reactions, bonding, and applications in engineering.",
    author:"Jain & Jain",
    price: 200,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh7MEu-jzWxn7tVwqLdfd9AJTHaZCsZpbmAQ&s",
    category: "Science",
    quantity:1,
  },
  {
    title: "Database Systems",
    description: "A practical introduction to SQL, relational databases, and data modeling.",
    author:"Raghu Ramakrishnan",
    price: 320,
    imageUrl: "https://covers.openlibrary.org/b/id/15125704-L.jpg",
    category: "Technology",
    quantity:1,
  },
  {
    title: "Digital Logic Design",
    description: "Fundamentals of logic gates, combinational and sequential circuits.",
    author: "M. Morris Mano",
    price: 250,
    imageUrl: "https://covers.openlibrary.org/b/id/6622129-L.jpg",
    category: "Technology",
    quantity:1,
  },
  {
    title: "Mechanical Engineering Basics",
    description: "Covers thermodynamics, fluids, and basic machine design.",
    author: "R.K. Rajput",
    price: 350,
    imageUrl: "https://covers.openlibrary.org/b/id/5250418-L.jpg",
    category: "Science",
    quantity:1,
  },
  {
    title: "Programming in C",
    description: "Best book to learn basics of programming, pointers, functions, and structures.",
    author:"Dennis Ritche",
    price: 180,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCh5Xl5weeYtEGqDWmm7zZcdpbIx8sZrVkSw&s",
    category: "Technology",
    quantity:1,
  },
  {
    title: "Java Complete Reference",
    description: "Explains OOP concepts, Java APIs, and real-world programming examples.",
    author:"Herbert Schildt",
    price: 400,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmogknZDXY1CaFzmHuGqJferX_FoYzo0_GXQ&s",
    category: "Technology",
    quantity:1,
  },
  {
    title: "Signals and Systems",
    description: "Mathematical foundation for analyzing electrical signals and transformations.",
    author:"Alan V. Oppenheim",
    price: 330,
    imageUrl: "https://covers.openlibrary.org/b/id/12627757-L.jpg",
    category: "Science",
    quantity:1,
  },
  {
    title: "Mathematics for Engineers",
    description: "Covers calculus, linear algebra, and differential equations.",
    author: "B.S. Grewal",
    price: 280,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPRQt9RDnZYt6GBz2D0CccTV1aXRwfPcmxeA&s",
    category: "Mathematics",
    quantity:1,
  },
  {
    title: "Environmental Science",
    description: "Explains ecological balance, sustainability, and environmental protection.",
    author:"G. Tyler Miller",
    price: 150,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSziscyy0Zq013M8hLgZltDk3BleztzXyq1Q&s",
    category: "Science",
    quantity:1
  },
];
module.exports={data:sampleBooks};